name: worktracker_pro
description: A multilingual remote work tracking app with GPS logging.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.5
  shared_preferences: ^2.0.15
  geolocator: ^9.0.2
  permission_handler: ^10.4.3
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  intl: ^0.17.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  json_serializable: ^6.5.4
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700